<?php

function displaystudent_theme($existing, $type, $theme, $path){
    return [
        'displaystudentlist' => [
            'variables' => [
                'title' => '',
                'details' => [],
                'absentcount' => [],
                'presentcount' => [],
                'absentstudent' => [],
                'form' => ''
            ]
        ]
    ];
}

?>